### ISSUE TITLE
Request Payload

### ISSUE THREAD

**Issue by steveops** [sirdarckcat/sirdarckcat.github.io#1]
Is there a way to modify the request payload?

**Comment by sirdarckcat** [comment]
Hi

Where? In the service worker script?

Yes, just in info param put a data property with the string you would like to send.

**Comment by steveops** [comment]
When a request is intercepted, I am able to redirect it to a new url. Is there a way to modify its payload also before rerouting?

**Comment by sirdarckcat** [comment]
Yes, for example, here:
https://sirdarckcat.github.io/#/service-worker

Select "fetch", then on URL put:
/sw/fetch?url=https://httpbin.org/post&init={"method":"POST","body":"bar"}

Then put in the options, configure method:POST and body:foo

You will see that the request was made with "bar" rather than "foo"

![image](https://cloud.githubusercontent.com/assets/33089/21546435/0b2ee1b8-cddf-11e6-9db0-5c9a2f512288.png)

**Comment by steveops** [comment]
Hello, am finding it hard to understand whats going on there. Is that another tool altogether or is is part of tamper? Could you please explain in simple terms how to proceed from this menu:
![capture](https://cloud.githubusercontent.com/assets/12711215/21548097/27ae4916-cdfb-11e6-92eb-8c33051f12a6.PNG)

**Comment by sirdarckcat** [comment]
Ah, you want to ask that here: https://groups.google.com/forum/#!forum/tamper-chrome-help =)

I didn't know what you were talking about.

To answer your question - Chrome doesn't expose any APIs to do that, but I'm trying to make it work anyway.

What you can do instead is to:
 1. Enable "Replay Requests (Experimental)"
 2. Enable "Block / Reroute Requests"
 3. BLOCK the request you want to modify.
 4. Edit the request you blocked.

This is very similar to what you asked for.

**Comment by steveops** [comment]
Ok thanks, I'll try that.

**Comment by sirdarckcat** [comment]
let me know how it goes!

**Comment by steveops** [comment]
Sure, I will.
